version: "3"

services:
  info_bot:
    image: yorky0/samgik-info-bot:latest
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
    environment:
      - SECRET_TOKEN=token
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 --scope myscope
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
